version: "3.1"

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: scrum-board
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres-password
    ports:
      - "5432:5432"


secrets:
  postgres-password:
    file: postgres-password.txt